### ISSUE TITLE
Use of uninitialized value error

### ISSUE THREAD

**Issue by kodayu** [likelet/LncPipe#3] opened 2018-04-20 03:16 UTC
It seems that there is something wrong with the module 'Identify_novel_lncRNA_with_criterions (1)'. It reportes an error while reading the first line of the GTF file, the command line is 'perl /data1/yukai/LncPipeLine20180404/LncPipe/bin/extract_gtf_by_name.pl merged.gtf - >novel.longRNA.gtf', and I find that the fist line of 'merged.gtf' is annotated by '#', maybe you should check the 'extract_gtf_by_name.pl' and take this situation into consideration.

**Comment by likelet** [comment] 2018-04-20 05:42
This is mainly caused by "#" in your merged.gtf,  thanks for your suggestion, 'extract_gtf_by_name.pl'  has been modified @kodayu

**Comment by likelet** [comment] 2018-04-20 05:43
cbe29a6076581360bb662e3b58bff7f676115f38

**Closed as completed** 2018-04-20 05:44 UTC
Labels: bug
