### ISSUE TITLE
LncPipeReporter (Generating report ...)` terminated with an error  exit status (1)

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#8] opened 2018-08-09 09:38 UTC
```
Aug-09 02:25:52.700 [Task monitor] ERROR nextflow.processor.TaskProcessor - Erro
r executing process > 'Run_LncPipeReporter (Generating report ...)'

Caused by:
  Process `Run_ #LncPipeReporter (Generating report ...)` terminated with an error
 exit status (1)

Command executed:

  Rscript -e "library(LncPipeReporter);run_reporter(input='.', output = 'reporte
r.html',output_dir='./LncPipeReports',de.method='deseq2',theme = 'npg',cdf.perce
nt = 10,max.lncrna.len = 10000,min.expressed.sample = 50, ask = FALSE)"

Command exit status:
  1
-----
Oops... Pipeline execution stopped with the following message: 

processing file: reporter.Rmd


processing file: ./Hisat2.Rmd


processing file: ./deseq2.Rmd
converting counts to integer mode
Quitting from lines 9-27 (./deseq2.Rmd) 
Quitting from lines NA-98 (./deseq2.Rmd) 
Error in counts(dds) : could not find function "counts"
Calls: run_reporter ... withVisible -> eval -> eval -> rowSums -> is.data.frame
Execution halted
```
PFA my nextflow.log.  I have a kallisto.count.txt file ~ 4.6MB in my work dir. any thoughts on this? 

[nextflow.log.txt](https://github.com/likelet/LncPipe/files/2273608/nextflow.log.txt)

[nextflow.log.txt](https://github.com/likelet/LncPipe/files/2273606/nextflow.log.txt)

**Comment by likelet** [comment] 2018-08-09 12:48
hi，i have never meet this before, but i am sure that the error is from the lncpipereporter. i have contacted the author of the package,  he will figure it out soon. can you plz send the count table to me by mail: zhaoqi@sysucc.org.cn ? we are appreciated that you can help us to improve our software

**Comment by bioinformatist** [comment] 2018-08-09 15:21
Hi, it's LncPipeReporter's author here.
It seems like a problem caused by NAMESPACE of my package.
Could you provide us your count table? No matter my bro's email above or mine <sun_yu@mail.nankai.edu.cn> is ok.
Thank you :smile:

**Comment by bioinformatist** [comment] 2018-08-10 14:57
This bug has been fixed. If you're using our docker image, pls pull it again about two hours later (it needs time for rebuilding).

**Comment by sateeshperi** [comment] 2018-08-10 15:05
After pulling the new docker image, can i '-resume' or will it re-run pipeline again?

**Comment by likelet** [comment] 2018-08-10 15:36
yes,  you can use `-resume` option

**Comment by sateeshperi** [comment] 2018-08-11 00:11
I ran into the same error even after pulling the latest docker image. I sent you the nextflow.log_0810.txt by e-mail. Do let me know if I am doing something wrong. @bioinformatist @likelet

**Comment by likelet** [comment] 2018-08-11 03:59
that is weird, we will check the log ASAP

**Comment by bioinformatist** [comment] 2018-08-14 07:52
Please pull the latest doker image then try again. Sorry for inconvenience.

**Comment by sateeshperi** [comment] 2018-08-14 23:50
ok

**Comment by sateeshperi** [comment] 2018-08-15 00:54
Have a new error running LncPipeReporter, I sent the 081418_nextflow.log to your e-mails. let me know if you are able to find the bug. Thanks

**Comment by likelet** [comment] 2018-08-15 02:50
get

**Comment by likelet** [comment] 2018-08-15 04:35
@sateeshperi hi, can you plz also send the `design.file` to me to reproduce the errors? You can just paste it in reply.
 Thanks~

**Comment by bioinformatist** [comment] 2018-08-15 10:02
@sateeshperi It seems you're using LncPipe of old version. Its output data had some problems. You may get latest LncPipe using `git pull` and then pull the latest docker image again. Thanks.

**Comment by sateeshperi** [comment] 2018-08-15 13:41
Here is my design.file:
```
Fertile:AAhu-FFfer-TTsp-SS1,AAhu-FFfer-TTsp-SS2,AAhu-FFfer-TTsp-SS3,AAhu-FFfer-TTsp-SS4
Infertile:AAhu-FFinfer-TTsp-SS2,AAhu-FFinfer-TTsp-SS3,AAhu-FFinfer-TTsp-SS5,AAhu-FFinfer-TTsp-SS6,AAhu-FFinfer-TTsp-SS7,AAhu-FFinfer-TTsp-SS8,AAhu-FFinfer-TTsp-SS9,AAhu-FFinfer-TTsp-SS10
```

**Comment by sateeshperi** [comment] 2018-08-15 13:43
The latest build on Docker hub from 4hrs ago has an Error status, can i use this?

**Comment by sateeshperi** [comment] 2018-08-15 13:49
$ docker pull bioinformatist/lncpipe
Using default tag: latest
latest: Pulling from bioinformatist/lncpipe
Digest: sha256:8c544ec868749550a9eb4c6dc5e14bbb882a3866a0f996c995265bf4a7e13dc4
Status: Image is up to date for bioinformatist/lncpipe:latest

**Comment by likelet** [comment] 2018-08-16 03:05
@sateeshperi not that version, the latest build did not success, plz wait few fours, we will rebuilt ASAP.

**Comment by bioinformatist** [comment] 2018-08-16 05:52
@sateeshperi We're sorry that the last docker image building is failed due to the poor network between docker hub and hisat2 (one of the dependencies of our pipeline) archive server. It's my carelessness that missed this status. I've re-triggered the building, and it do finish successfully now. You could pull it and try again.

**Comment by likelet** [comment] 2018-08-16 08:27
plz also pull the latest lncPipe to rerun your analysis by `-resume` function

**Comment by sateeshperi** [comment] 2018-08-16 14:27
Getting this new error: 
```
$ nextflow -c docker.config run LncRNAanalysisPipe.nf -resume
N E X T F L O W  ~  version 0.31.0
Launching `LncRNAanalysisPipe.nf` [voluminous_lamport] - revision: 003a48066e
ERROR ~ expecting '}', found 'else' @ line 1164, column 6.
       }else if (params.species=="mouse"){
        ^

1 error


 -- Check '.nextflow.log' file for details
```

**Comment by likelet** [comment] 2018-08-16 16:19
sorry... a mistake of missing letter `i` in 
https://github.com/likelet/LncPipe/blob/f6810b54ea145fe7eafadc976be4716e86636b56/LncRNAanalysisPipe.nf#L1157
you can fix it in `nf` file (add an `i` letter)  or try pull again,

**Comment by sateeshperi** [comment] 2018-08-16 18:01
Also the .nf file seems to be missing a '}' at line 1601. I added it and was able to launch the workflow

**Comment by sateeshperi** [comment] 2018-08-16 18:02
I had to change some reference files so, I am running the pipeline from the beginning. Will update you on how it goes.

**Comment by sateeshperi** [comment] 2018-08-16 21:16
```
ERROR ~ Error executing process > 'Rerun_CPAT_to_evaluate_lncRNA (1)'

Caused by:
  No such property: design for class: nextflow.script.FileInParam

Source block:
      if(params.species=="human"){
          '''
          cpat.py -g !{lncRNA_final_cpat_fasta} \
                                         -x !{params.cpatpath}/dat/Human_Hexamer.tsv \
                                         -d !{params.cpatpath}/dat/Human_logitModel.RData \
                                         -o lncRNA.final.CPAT.out
          '''
      }else if (params.species=="mouse"){
          '''
          cpat.py -g !{lncRNA_final_cpat_fasta} \
                                         -x !{params.cpatpath}/dat/Mouse_Hexamer.tsv \
                                         -d !{params.cpatpath}/dat/Mouse_logitModel.RData \
                                         -o lncRNA.final.CPAT.out
          '''
  
      }else if (params.species=="zebrafish"){
          '''
          cpat.py -g !{lncRNA_final_cpat_fasta} \
                                         -x !{params.cpatpath}/dat/zebrafish_Hexamer.tsv \
                                         -d !{params.cpatpath}/dat/zebrafish_logitModel.RData \
                                         -o lncRNA.final.CPAT.out
          '''
      }else {
          '''
          cpat.py -g !{lncRNA_final_cpat_fasta} \
                                         -x !{params.cpatpath}/dat/fly_Hexamer.tsv \
                                         -d !{params.cpatpath}/dat/fly_logitModel.RData \
                                         -o lncRNA.final.CPAT.out
          '''
  
  }
```

**Comment by likelet** [comment] 2018-08-17 01:13
i can not reproduce this error, but i came accrocess another error in the same line , also fixed this. 
BTW, i added a new feature to help to skip the alignment and assembly proces, which take too much time. 
if you have this error, means you have alread run the assemble step, plz mv the `merged.gtf ` from you result folder   like 
```
     ln -s Result/Merged_assemblies/merged.gtf .
```
and then rerun the pipe by 
```
nextflow -c docker.config run LncRNAanalysisPipe.nf --merged_gtf merged.gtf -resume --qctools none
```

`--qctools` none means you will skip you qc process in quantification step. 

sorry again for my mistake, try git pull lncPipe again.  

Qi

**Closed as completed** 2018-08-17 17:40 UTC
Labels: bug, enhancement

**Comment by brunohhomem** [comment] 2019-08-06 11:13
Hi, how are you guys?
I'm having the same problem like @sateeshperi .
I'm running mouse data, with the latest docker image, nextflow version and lncpipe git. Someone can help me?
[pipe.txt](https://github.com/likelet/LncPipe/files/3471849/pipe.txt)
I'm running two samples at a time, more than two samples we can't run because my server is weak.
I've tried with other samples and with new ref files.

Can I use the generated files without the lncPipeReporter step? If I can't fix this issue, maybe there is another way to work with the generated data? I'm assuming that the data was generated because my issue is on reporter step.
